#!/usr/bin/env bash
set -e  # exit on error
set -x  # show commands, expand variables when executing

database_path=${DB_URL##*/}
database_name=${database_path%%\?*}

mysql -e "create database $database_name;"
mysql -e "create user '$DB_USER'@'localhost' identified by '$DB_PASSWORD';"
mysql -e "grant all privileges on $database_name.* to '$DB_USER'@'localhost';"
mysql -e "flush privileges;"

# References

# Setup MySQL database w/ a Bash script: https://stackoverflow.com/a/33474729/2675670
# Parsing a URL: https://stackoverflow.com/a/5497428/2675670
