#!/usr/bin/env bash
set -e

database_path=${DB_URL##*/}
database_name=${database_path%%\?*}

mysql -e "drop database $database_name;"
mysql -e "revoke all privileges, grant option from '$DB_USER'@'localhost';"
mysql -e "drop user '$DB_USER'@'localhost';"
mysql -e "flush privileges;"
