#!/usr/bin/env bash
set -e

database_path=${DB_URL##*/}
database_name=${database_path%%\?*}

mysql -e "show databases like '$database_name';"
mysql -e "select host, user from mysql.user where user like '$DB_USER';"
mysql -e "show grants for '$DB_USER'@'localhost';"
mysql "$database_name" -e "show tables;"
