#!/usr/bin/env bash
set -e

usage="usage: ./util/db_undo_migration path/to/migration/UYYYYMMDDHHMMSS_file.sql"

database_path=${DB_URL##*/}
database_name=${database_path%%\?*}

migration_filename=$1
if [ ! -f "$migration_filename" ]; then
    echo "$usage"
    exit 0
fi

mysql \
    --user="$DB_USER" \
    --password="$DB_PASSWORD" \
    "$database_name" \
    < "$migration_filename"
